### ISSUE TITLE
Implement Task-agnostic metrics

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#10]
- No. parameters (used in #4)
- No. layers (used in #6) - transformer equivalent probably no. blocks

**Comment by eddableheath** [comment]
Fyi number of parameters is simply `model.num_parameters()` as it turns out.

**Comment by eddableheath** [comment]
I think I've duplicated the second part of this with [37](https://github.com/alan-turing-institute/ARC-LoCoMoSeT/issues/37). Still researching if there is a good understanding of a proxy for capacity to adapt in transformers, number of blocks could make sense but I wonder if the number attention heads could also be a factor?

**Comment by eddableheath** [comment]
Implemented in https://github.com/alan-turing-institute/ARC-LoCoMoSeT/commit/a91f9f1dc0132569a11db2927b1e19d0e74ea494

**Comment by eddableheath** [comment]
Closed by merge.
