### ISSUE TITLE
Setup Baskerville

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#14]
- [x] request project (ticket C2307-068)
- [x] request approved
- [x] Baskerville project created
- [x] setup environment

**Comment by jack89roberts** [comment]
Removing this from WP1

**Comment by eddableheath** [comment]
Proposed structure on baskerville (for both metric experiments and fine tuning):

1. Bash script that creates run specific configs within directory structure as defined by the #63.
2. Generation of slurm config file (just a `.txt`) by the above bash script, this will point the slurm script in the right direction for the config files, as well as letting it know how many config files are required to be read (i.e. size of array job).
3. Slurm script will read the `slurm_config.txt` file, using that to point the array jobs in the right direction.

**Comment by eddableheath** [comment]
Currently the simplest way to do this is to run the config generating script developed in #63, then pass `path/to/configs` and the number of configs to the slurm script manually. 

A slightly better (yet potentially somewhat hacky...?) way - that I used to do using hpc's previously is have a template array job script that is edited using `sed`. I think this is probably worthwhile though?

**Comment by eddableheath** [comment]
Current functionality is a script that will generate all the configs then adapt a slurm (currently draft) job script template. Further steps:

- [x] Finish slurm array job.
- [x] Decide on if `bask_metric_exp_set_up.sh` script will submit the slurm jobscript as well or if this this should be done by hand?
- [ ] Tests?
- [ ] Generalise the job script/write equivalent one for the training scripts (these require equivalent scripts for config gen too..)

**Comment by eddableheath** [comment]
Further questions to answer:

- [x] Are we using GPUs for inference? Will need to refactor `models/load.py` for reflect this if so.
- [x] Typically on HPC systems (including baskerville) conda is the go to environment, it is possible to use `pip` and `venv` but becomes a little fiddly, we should settle on using one or the other on baskerville.

**Comment by eddableheath** [comment]
On a further investigation it might be more straightforward to use pip and virtualenv, however we should consider whether each array job is going to set up a new environment or if it just activates an already extant one.

**Comment by eddableheath** [comment]
The baskerville slurm array jobs don't seem to work, a common problem among clusters as `${SLURM_ARRAY_TASK_ID}` doesn't have a value. This seems to be a consistent problem with baskerville according to others I've spoken to, so will be using an alternative method.

**Comment by eddableheath** [comment]
The baskerville environment and scripts are working now, including connecting to wandb, but for some reason are not going to the right place in wandb.

**Comment by eddableheath** [comment]
Things to look into:

- [x] Caching datasets baskerville from huggingface
- [x] Caching models on baskerville from huggingface

https://huggingface.co/docs/datasets/cache

**Comment by eddableheath** [comment]
Caching datasets is fairly straightforward, following the link above simply passing a directory path (now in the config) to `load_dataset` caches the datasets in the right place.

For the models there isn't an equivalent argument to pass and it looks like from [here](https://huggingface.co/docs/huggingface_hub/guides/manage-cache) and [here](https://huggingface.co/docs/transformers/v4.34.1/en/installation#cache-setup) that we need to set the cache as an environment variable in the shell. It also looks like there is a fairly complex directory structure for this, but it's unclear to me how much of that is automatically set up.

**Comment by eddableheath** [comment]
Setting the cache as an environment variable doesn't appear to be working, might have have an additional part of `load_model` which manually caches/checks for a cache.

**Comment by jack89roberts** [comment]
I think the model loading functions should also accept a `cache_dir` argument (but the env variables _should_ be a pretty neat way to do it)

**Comment by eddableheath** [comment]
I was having problems with it, but by adding the following lines to the end of your `.bashrc` file in your home directory on baskerville it should work:

>`# set the transformers and dataset cache variable`
>`export TRANSFORMERS_CACHE="/bask/projects/v/vjgo8416-locomoset/ARC-LoCoMoSeT/.cache/huggingface/models"`
>`export HF_DATASETS_CACHE="/bask/projects/v/vjgo8416-locomoset/ARC-LoCoMoSeT/.cache/huggingface/datasets"`

**Comment by eddableheath** [comment]
It's now got both methods for both datasets and models, so setting the env variables shouldn't be strictly necessary. However, I've noticed that if you don't do that whilst the datasets and models end up in the right place, there is still a huggingface dir in the standard `.cache` in the personal home directory which gets generated and filled with details about the downloads, so worth setting them anyway.

**Comment by eddableheath** [comment]
Todo:

- [ ] Check that full pipeline of config generation and job running works.

**Comment by eddableheath** [comment]
Todo:

- [x] Check full pipeline of config generation and jobsubmission works on baskerville.
- [ ] Tidy up directory.
- [ ] Documentation/docstrings where relevant.
- [x] Pull together PR (including this and #63)
