### ISSUE TITLE
Code to work for non-streaming and streaming datasets

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#17]
Make it so we can toggle streaming on/off in all the data processing functions.

I moved an old draft function to https://github.com/alan-turing-institute/ARC-LoCoMoSeT/tree/17-streaming-data

**Comment by eddableheath** [comment]
This shouldn't be too hard to adapt, now we've got the `MetricExperiment` class as a modular design. Some refactoring required, but I thinking turing the `MetricExperiment` into a base class, with child classes for streaming and non streaming data, then adapting the config to have a streaming flat and `run_metrics.py` to create an instance of the right class should be fine.

[This should als be possible to incorporate for training](https://huggingface.co/docs/datasets/stream#stream-in-a-training-loop).

**Comment by jack89roberts** [comment]
I think non-streaming will be better for Baskerville so we probably don't need to worry about this for now. But I also suspect it wouldn't need to be changed much apart from tweaking how we extract the labels and maybe a small change to `get_features`.

**Comment by eddableheath** [comment]
Moving this to workpackage 3B as not necessary for baskerville set up.

**Comment by jack89roberts** [comment]
I think let's just remove it from any milestone for now (I've done that), at least until we know we actually need it.
