### ISSUE TITLE
Script to run experiment using any metric

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#21]
Building off the separate scripts for PARC and Renggli, create an experiment-running script that can be configured to run either metric.

- [x] Config file to specify both which metric to use and the metric parameter values - required for WP1
- [x] Generate parameter values for each run in a nicer way than a load of nested for loops - nice to have WP1

**Comment by eddableheath** [comment]
I'm not going to vary over the feature reduction dimensions for now in the script, but I've left a comment for where we need to edit it for future reference.

**Comment by eddableheath** [comment]
See first pass in this commit:

https://github.com/alan-turing-institute/ARC-LoCoMoSeT/commit/fe2947a889cc231a5ce146cb4b2f33a7a49802b4

**Comment by jack89roberts** [comment]
Done pending #15 being merged.
