### ISSUE TITLE
Implement HuggingFace cache management

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#28]
The HuggingFace cache (by default `~/.cache/huggingface`) can get very large as it contains previously used models, datasets, and processed versions of datasets for each model.

We may want to:

- Change the location of the cache (at least when running on Baskerville)
- Remove cached processed datasets for each model once we have finished with that dataset for that model.
- Remove cached models themselves once we're done with that model.

See here for example: https://huggingface.co/docs/datasets/cache

**Comment by eddableheath** [comment]
Changing the cache locations are covered by #66.

Removing the caches when we're done with the datasets and models is not yet implemented, however we've not currently got a good signifier of when we're done with them.

**Comment by jack89roberts** [comment]
Could make this one just about setting the cache location, close it with #66, and make another issue for 3B just to remind us to monitor how much storage we're using etc.?

**Comment by eddableheath** [comment]
This issue is now solely about the caching location, with the other two consideration now covered by #68.

This will now be closed by #66.
