### ISSUE TITLE
debugging tests in vscode with pytest-cov

### ISSUE THREAD

**Issue by lannelin** [alan-turing-institute/ARC-LoCoMoSeT#31]
pytest-cov clashes with debuggers (https://pytest-cov.readthedocs.io/en/latest/debuggers.html). If you wish to debug tests in this project you should disable pytest-cov for these runs. In VSCode this can be achieved with the following run configuration added to `launch.json` (note, VSCode will just take the first configuration with the `"debug-test"` purpose so be wary of having > 1):
```
{
      "name": "Python: Debug Tests",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "purpose": ["debug-test"],
      "console": "integratedTerminal",
      "justMyCode": false,
      "env": {"PYTEST_ADDOPTS": "--no-cov"}
    }
```

not sure if this is worth concretely documenting in README, this issue may serve as sufficient documentation.
Will leave open for now and let you close if you're happy.

**Comment by jack89roberts** [comment]
For reference a whole `.vscode/launch.json` file might look like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Debug Tests",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "purpose": ["debug-test"],
            "console": "integratedTerminal",
            "justMyCode": false,
            "env": {"PYTEST_ADDOPTS": "--no-cov"}
          }
    ]
}
```
