### ISSUE TITLE
Use conventions for model inference in feature extraction code

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#32]
The way we're extracting the features from the models:

https://github.com/alan-turing-institute/ARC-LoCoMoSeT/blob/ad6a78029188699599bc2e99a6b237e24261fd42/src/locomoset/models/features.py#L25-L28

is not standard. Should be treating this as model inference rather than a data preprocessing step.

Also see this thread in the WP1 PR: https://github.com/alan-turing-institute/ARC-LoCoMoSeT/pull/15#discussion_r1288442150

**Comment by eddableheath** [comment]
The [pipeline](https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/pipelines#pipeline-custom-code) for transformers from huggingface appears to be a class intended to standardise inference methods, not sure how often it's used. I've seen it used on every diffusion model I've played around with, but little else.

**Comment by eddableheath** [comment]
I created [this branch](https://github.com/alan-turing-institute/ARC-LoCoMoSeT/tree/32-pipeline-tests) to play around with custom pipelines in a notebook, it appears to work and has a lot more we could achieve with it that I haven't tried yet.

**Comment by jack89roberts** [comment]
See `FeaturesPipeline` class in https://github.com/alan-turing-institute/ARC-LoCoMoSeT/blob/32-pipeline-tests/notebooks/pipeline_tests.ipynb

**Comment by jack89roberts** [comment]
I started to pull this out of the notebook yesterday and made a draft PR #38. Weirdly it seems the output of one iteration of the pipeline is always the features of a single image no matter the batch size (it's only the `_forward` function that sees the whole batch, the `postprocess` gets a single image). Will look into that, I assume/hope there's a proper way to be getting output from a pipeline for a whole dataset...

**Comment by jack89roberts** [comment]
The above is another streaming/non-streaming dataset quirk.

**Comment by jack89roberts** [comment]
Note to self after going down many rabbit holes today:

- The base `Pipeline` class has a check for whether the input is a dataset instance, which ultimately determines whether the pipeline will process the data one at a time, in batches, or all in one go. See [this block of code](https://github.com/huggingface/transformers/blob/e42587f596181396e1c4b63660abf0c736b10dae/src/transformers/pipelines/base.py#L1089-L1122).
- This is checking whether the input is an instance of a **`torch`** dataset (`torch.utils.data.Dataset`), ***not*** whether it is a HuggingFace **`datasets`** dataset (e.g. `datasets.arrow_dataset.Dataset`).
- HuggingFace **`Dataset`** (non-streaming, e.g. `datasets.arrow_dataset.Dataset`) ***do not*** have `torch` datasets as a parent class.
- Streaming HuggingFace datasets, i.e. **`IterableDataset`** (`datasets.iterable_dataset.IterableDataset`), ***do*** have `torch` datasets as a parent class.
- `datasets.load_dataset(<dataset_name>, streaming=True)`, which returns a `datasets.iterable_dataset.IterableDataset`, ***never*** uses local files
- `datasets.load_dataset(<dataset_name>, streaming=False)`, which returns a `datasets.arrow_dataset.Dataset`, uses local files only (and will download the whole dataset first if not present).
- A non-streaming dataset can be converted into a dataset that streams from local files using `dataset.to_iterable_dataset()`, which returns a `datasets.iterable_dataset.IterableDataset`.

To cut a long story short I think we will want to:

- Download the dataset and save it to the cache/load it non-streaming mode:
  ```python
  dataset = load_dataset(<dataset_name>, streaming=False)
  ```
  - When on Baskerville we'll then only need to download the dataset once across all experiments, then load it from the cache each time after that (but we'll need to keep an eye on the cache size)

- Convert the dataset to a locally streaming `IterableDataset`:
  ```python
  dataset_iter = dataset.to_iterable_dataset()
  ```

- Pass `dataset_iter` to the pipeline with the appropriate batch size etc.

Alternatively, we can make a one-line change `__call__` from the pipeline base class to make it check for instances of HuggingFace datasets or torch datasets. I think at minimum there's some HuggingFace docs that should be improved here so will consider next week if it's worth an issue/PR of some kind.

**Comment by jack89roberts** [comment]
In the end, I found a way to do it using `KeyDataset` (which also inherits from `torch.utils.data.Dataset`) and inheriting from `ImageClassificationPipeline`. Basically two lines of code...
