### ISSUE TITLE
Implement PARC capacity to train parameter.

### ISSUE THREAD

**Issue by eddableheath** [alan-turing-institute/ARC-LoCoMoSeT#37]
In addition to the feature reduction via PCA PARC has a capacity to train parameter for each model. For CNNs this is well estimated by the depth of the network, giving the capacity that the features have for adapting to changing in response for new data. This is unlikely to hold as a good estimate for Transformers, so some investigation to find a suitable alternative proxy is necessary.

The full adaptation only makes sense once we have a set of prediction scores over models for a given dataset as each score is z-normed with the capacity to change scaled by the max possible value.

This can also be applied to more than just PARC, so worth writing in such a way that it can be applied as such.

Todo:

- [x] Invesitgate Transformer based proxies for capacity to train.
- [ ] Implement adapatation of proxy for a given metric.

NB: This should be done before [36](https://github.com/alan-turing-institute/ARC-LoCoMoSeT/issues/36)

**Comment by jack89roberts** [comment]
I'd be inclined not to change the PARC implementation, but rather have separate functions/classes that allow combining metrics (with different weightings/normalisations).

**Comment by eddableheath** [comment]
This combination doesn't need to be included in the pipeline for anyone metric as it can be applied to the results as a post processing step since it is independent of the metric.

**Comment by eddableheath** [comment]
https://github.com/alan-turing-institute/ARC-LoCoMoSeT/commit/a91f9f1dc0132569a11db2927b1e19d0e74ea494 includes and implementation of the function for this based on the number of parameters. However it varies from the original in that the normalisation is over the models rather than over the datasets.

This has not be incorporated into the main pipeline yet.

**Comment by eddableheath** [comment]
Moving this to workpackage 3b for now as if we continue with this it will be implemented as a modifier on the results when running analysis for, not necessary to be implemented in the main metric experiment pipeline.

If this does seem to make a large difference we could consider adding it to the main experiment pipeline as an option for future use of this code.

**Comment by jack89roberts** [comment]
~~Like the other one, I think we can ignore this in all milestones unless something comes up that makes it worthwhile. The experimenting we did in WP1/2 suggested the hyperparamters didn't make much difference.~~

**Comment by jack89roberts** [comment]
Ah ignore me, I misread what the issue is about. Will leave this one in 3B for now.
