### ISSUE TITLE
`test_renggli_random_features` occasionally fails

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/ARC-LoCoMoSeT#50]
But if seeds, versions etc. are set correctly then it should give a reproducible result (expected that the result doesn't exactly match random performance, but the value should be consistent)

**Comment by jack89roberts** [comment]
e.g. see #41, [a758e0c](https://github.com/alan-turing-institute/ARC-LoCoMoSeT/pull/41/commits/a758e0c9bd40c825962d7f992af126a25ed65dff), and [this actions run](https://github.com/alan-turing-institute/ARC-LoCoMoSeT/actions/runs/6152079928/job/16693490741)

**Comment by jack89roberts** [comment]
Will be fixed by #52

**Comment by eddableheath** [comment]
Closed as fixed by #52 PR.
